// Generated by scripts/sync-version.mjs during deploy. Default values are used
// for local development; production/staging builds overwrite this file from the
// latest git tag before bundling.
export const APP_VERSION = '1.0.0'
export const APP_NAME = 'Memberr'
