// Sync the latest git tag into apps/mobile/app.json (expo.version + name) and
// apps/mobile/lib/appInfo.ts (build-time constants). Run automatically before
// `deploy:web` so the web build matches the current tag.
import { readFileSync, writeFileSync } from 'fs'
import { execSync } from 'child_process'

const appJsonPath = 'apps/mobile/app.json'
const appInfoPath = 'apps/mobile/lib/appInfo.ts'
const cfg = JSON.parse(readFileSync(appJsonPath, 'utf8'))

let tag
try {
  tag = execSync('git describe --tags --abbrev=0', { encoding: 'utf8' }).trim()
} catch {
  console.error('ERROR: No reachable git tag found. `deploy:web` requires a tag to set the web app version.')
  console.error('Run `git fetch --tags` and ensure the current checkout has a tag, or tag the release first.')
  process.exit(1)
}

const version = tag.startsWith('v') ? tag.slice(1) : tag
const isBeta = tag.includes('-beta')
const appName = isBeta ? 'Memberr Beta' : 'Memberr'

cfg.expo.version = version
cfg.expo.name = appName

const appInfo = `// Generated by scripts/sync-version.mjs during deploy. Do not edit manually.
export const APP_VERSION = '${version}'
export const APP_NAME = '${appName}'
`

writeFileSync(appJsonPath, JSON.stringify(cfg, null, 2) + '\n')
writeFileSync(appInfoPath, appInfo)
console.log(`Synced version from tag ${tag} → version: ${version}, name: ${appName}`)